//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordrobeMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public int ClothingID { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> OccassionID { get; set; }
        public Nullable<int> SeasonID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Occassion Occassion { get; set; }
        public virtual Season Season { get; set; }
        public virtual Type Type { get; set; }
    }
}
